"""init

Revision ID: dd317ef023af
Revises:
Create Date: 2026-05-02 21:10:27.995834

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dd317ef023af"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
